#!/usr/bin/env sh
set -eu

DOCKER_BUILDKIT=1 docker build . -t dd-dicetron

if [ "$1" == "push" ]; then
	docker tag dd-dicetron oleobal/dd-dicetron:latest
	docker push            oleobal/dd-dicetron:latest
fi